### ISSUE TITLE
What is the purpose of separating NPM dependencies?

### ISSUE THREAD

**Issue by ryanmortier** [driesvints/laravel#3]
Referring to this commit: 35dc36a6c52c67b1d74a33968fd7acae9e24d47a

Also, why do you leave `cross-env` as a dev dependency since even in production you'll have to `npm run production` which uses this package?

**Comment by driesvints** [comment]
Heya, thanks for asking. It makes a clear distinction between dependencies which are used in your projects production codebase and the ones which are meant for building or development. `cross-env` is only used when building assets and not as a dependency for your app's code to run.

**Comment by ryanmortier** [comment]
Ok thanks!
